- README.rdoc
The correct link is `stack.html` instead of `call_stack.html`
> Fix link to call stack example in README

- bin/ruby-prof
The path for the reports directory is given in `--file=path`.  If no
such argument is given, it defaults to the current directory.
> Add --printer=multi command-line option

- lib/ruby-prof/rack.rb
- test/rack_test.rb
Mainly to make it possible to run a bunch of profiling requests sequentially,
to generate automated benchmarks.
Unit tests on that new feature, and beefed up the tests on the Rails adapter.
> Making it possible to pass lambdas for the path the Rails profiler adapter writes to

- ext/ruby_prof/extconf.rb
MRI >= 1.9 should set this to 'ruby' correctly.
This will catch jruby, macruby, rbx, maglev, ironruby, cardinal and
any other non-MRI ruby out there which this gem does not support.
> just use RUBY_ENGINE != 'ruby'

- README.rdoc
- ext/ruby_prof/rp_measure_cpu_time.c
Open conditional in rp_measure_cpu_time.c to accept non-gnu-c in addition.
Previously failing on AIX 6.1.
Before:
```
bash-4.2# gmake
compiling rp_measure_cpu_time.c
"rp_measure_cpu_time.c", line 103.24: 1506-045 (S) Undeclared identifier measure_cpu_time.
Makefile:224: recipe for target 'rp_measure_cpu_time.o' failed
gmake: *** [rp_measure_cpu_time.o] Error 1
bash-4.2# gmake clean
bash-4.2# gmake
compiling rp_call_info.c
compiling rp_measure.c
compiling rp_measure_allocations.c
compiling rp_measure_cpu_time.c
"rp_measure_cpu_time.c", line 103.24: 1506-045 (S) Undeclared identifier measure_cpu_time.
Makefile:224: recipe for target 'rp_measure_cpu_time.o' failed
gmake: *** [rp_measure_cpu_time.o] Error 1
```
After:
```
bash-4.2# gmake
compiling rp_measure_cpu_time.c
compiling …
```
> Allow for compilation of rp_measure_cpu_time.c with non-gnu-C

- bin/ruby-prof
- lib/ruby-prof/compatibility.rb
The default value of the measure mode is `RubyProf::WALL_TIME`.
https://github.com/ruby-prof/ruby-prof/blob/master/lib/ruby-prof/compatibility.rb#L52
```ruby
def self.measure_mode
@measure_mode ||= RubyProf::WALL_TIME
end
```
Correct some mistakes in comments.
> Correct some mistakes in comments

- lib/ruby-prof/assets/call_stack_printer.js.html
This fixes a bug I noticed: `Uncaught TypeError: Cannot read property 'match' of null` in method `aboveThreshold`, line `var match = text.match(/\d+[.,]\d+/);`. Checked in Chrome 47.0.2526.106.
> Fixed null text node bug

- lib/ruby-prof.rb
- lib/ruby-prof/profile.rb
Improve startup time and memory by not loading printers that never get used.
> Use autoload for printers

- README.rdoc
* Add note that ruby-prof must be reinstalled to take advantage of patches
* Break patch info into its own section to be easier to find
> Improve patching notes in README

- README.rdoc
Found this minor typo in the README.
> Fix typo 'Rubyprof' in README

- README.rdoc
Is there more documentation than this? I looked for documentation on the executable in generated docs / readme / github wiki before trying the executable itself.
> Clarify how to view executable documentation

- .gitignore
- ext/ruby_prof/extconf.rb
- ext/ruby_prof/rp_method.c
- ext/ruby_prof/rp_method.h
- lib/ruby-prof/printers/call_tree_printer.rb
- test/no_method_class_test.rb
- test/printers_test.rb
Last year, we at Airbnb started encountering problems that required serious profiling work.  Luckily, `ruby-prof` was there to help.  While using it, we iterated on internal patches to get the results we desired.  The time has come to offer these up in the hopes that they may be useful to others.
This is the first patchset in the series and is the base on which we built the other patches.  This fixes a few bugs we encountered with GC, enables C99 support, begins making some changes to MethodInfo that will come into play later, and tweaks the way methods are named for callgrind output.
KCacheGrind is designed for C++ and many of its features expect C++ style names.  Faking Ruby names into C++ allows the class groupings to work, for instance.  This requires `Foo::Bar#baz` to be rendered as …
> Minor cleanup and KCacheGrind friendlier naming

- .gitignore
- ext/ruby_prof/extconf.rb
- ext/ruby_prof/rp_call_info.c
- ext/ruby_prof/rp_call_info.h
- ext/ruby_prof/rp_method.c
- ext/ruby_prof/rp_method.h
- ext/ruby_prof/rp_stack.c
- ext/ruby_prof/rp_stack.h
- ext/ruby_prof/ruby_prof.c
- lib/ruby-prof/call_info.rb
- lib/ruby-prof/method_info.rb
- lib/ruby-prof/printers/call_info_printer.rb
- lib/ruby-prof/printers/call_tree_printer.rb
- lib/ruby-prof/profile.rb
- lib/ruby-prof/thread.rb
- test/aggregate_test.rb
- test/no_method_class_test.rb
- test/printers_test.rb
- test/recursive_test.rb
Refer to https://github.com/ruby-prof/ruby-prof/pull/200 for more context.
We encountered SystemStackErrors during the post processing phase when
using the recursive ruby definition of recursion detection.  The post
processing phase is also rather time consuming because it requires
turning the `prof_call_info_t` structs into full Ruby objects.
This commit addresses both issues by performing the logic of
`CallInfo#detect_recursion` but from the stack operations during
profiling.
/cc @skaes @nelgau
> Detect recursive contexts during profiling

- lib/ruby-prof/rack.rb
- test/rack_test.rb
If using the Rack middleware to process a lot of requests, it can be quite
a pain to make sense of the sheer volume of files generated (one per request).
This patch adds a new `:max_requests` to the middleware, which will then
starts aggregating profiles across requests and will only dump the result file
when it has profiled `:max_requests` requests or when the current process shuts
down, whichever happens first.
Kept total backward compatibility.
Added tests on the new feature.
> Making it possible to aggregate several requests in the Rack middleware

- .travis.yml
This bumps the version numbers in the travis config to the latest.
Would there be merit in also adding ruby-head but allowing it to fail so we can track progress toward compatibility?
> update to latest rubies on travis

- lib/ruby-prof/printers/graph_html_printer.rb
- lib/ruby-prof/printers/graph_printer.rb
Ruby 2.5 is pickier about sprintf formatting and will raise the error linked below without this change to how sprintf is called.
https://github.com/ruby/ruby/commit/d9d2bbe4b92120003cc026176a3841c875378e7c#diff-050ece9ea0cea6d9c95cafd7ffe8de43R524
> correctly escape % in sprintf

- lib/ruby-prof/printers/call_stack_printer.rb
if `RUBYOPT=--enable-frozen-string-literal`, this breaks.
> make thread_info modifiable

- README.rdoc
**NB**: I am not entirely positive this is right, but it is the path
that got me to code that can execute. If I am mistaken in my approach, please
let me know.
RubyProf is a module and, thus, does not provide a method for
constructing class instances. RubyProf::Profile is the the class that
provides an interface into the core profiling API.
> Ensure README provides executable code.

- lib/ruby-prof/profile/legacy_method_elimination.rb
read_regexps_from_file() read the file but never returned the regular
expressions that it read.
> Fix -X/--exclude-file option not working.

- lib/ruby-prof/printers/abstract_printer.rb
- test/abstract_printer_test.rb
It's currently impossible to have the printer print bare file paths under macOS. 
Due to a bug, both configuration methods (env and passing options) only make a change when they are not `false` / `nil`.
This change makes it possible to have bare file paths printed either when `:editor_uri` key is set to false or when `RUBY_PROF_EDITOR_URI` env is set and empty.
Additionally, a exhaustive test case is added for this method of `AbstractPrinter`.
> Adjust AbstractPrinter#editor_uri so it's possible to disable uri

- ext/ruby_prof/ruby_prof.c
- ext/ruby_prof/ruby_prof.h
- lib/ruby-prof/compatibility.rb
- test/exceptions_test.rb
Possible solution to #238 
I think it is a Bad Idea to suppress all exceptions encountered while in the block passed to Profile#profile, but I can see the logic behind suppressing these exceptions.
I've added a new option: `allow_exceptions` which behaves in the following way:
allow_exceptions defaults to false and RubyProf will continue to
suppress all exceptions in this mode and always return a Profile object
If allow_exceptions is set true, RubyProf will raise any exceptions
encountered during profiling and will not return a Profile object
> Add "allow_exceptions" option to Profile

- ext/ruby_prof/rp_measure_process_time.c
This PR fixes compilation on older OSX. `clock_gettime` was introduced since [OSX Sierra 10.12](http://www.manpagez.com/man/3/clock_gettime/).
Test on newer macs with both getrusage and clock_gettime gave me quite similar results and tests passed.
El Captain is almost 4 years old now, but some models stuck with El Captain and upgrading dev environment is always a PITA.
> measure_process_time: fallback to getrusage

- lib/ruby-prof.rb
This class appears to have been removed in b9e83413237beacfc8466bc8319bb9935ca6fc6b.
Thanks
> Remove obsolete autoload for `AggregateCallInfo`

- ruby-prof.gemspec
Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/ruby-prof), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
> Add project metadata to the gemspec

- lib/ruby-prof/printers/abstract_printer.rb
- lib/ruby-prof/printers/flat_printer.rb
- test/printer_flat_test.rb
These options are complementary: max_percent adds the ability to exclude results over a particular threshold. filter_by allows the results to be filtered (using min_percent and max_percent) by a different metric than self_time.
Using `filter_by: :total_time, max_percent: 90` (for example) is a convenient way to exclude items from the top of the call stack that might not be very interesting, and simply wrap expensive calls further down.
Addresses https://github.com/ruby-prof/ruby-prof/issues/267.
> Add max_percent and filter_by options

- lib/ruby-prof/printers/graph_html_printer.rb
Fixing a small typo:
s/min_perecent/min_percent
> Correct typo: s/perecent/percent

- .github/workflows/testing.yml
The comment in the `setup-ruby` action step before mentions 'bundle install' having happened already.
> CI: Omit duplicate 'bundle install'

- .github/workflows/testing.yml
Due to an issue with the yaml parser used by Actions, elements like `3.0` and `3.10` are treated as numbers, and the trailing zero is truncated.  Hence, `3.0` becomes `3`.  So, the Ruby version selected is probably not intended.
See https://github.com/ruby-prof/ruby-prof/actions/runs/3403477040/jobs/5660027501#step:3:15 which incorrectly selects Ruby 3.1.2.
1. Fix above by quoting `3.0`.
2. Add Ruby mswin to matrix.  I noticed some commits referencing msvc, the mswin build is a msvc build of Ruby head.  At present, no release versions are available with GitHub Actions.
When running Actions CI in my fork, results were intermittent.
> Actions - change 3.0 to '3.0', add Windows mswin

- lib/ruby-prof/compatibility.rb
Fixes #332.
This PR updates the deprecation warning for `RubyProf.measure_mode=`, which currently suggests using `RubyProf::Profile#measure_mode=`, but causes a `NoMethodError`. The warning now correctly recommends using `RubyProf::Profile.new(measure_mode: ...)` as the proper pattern.
> Fix deprecation warning for RubyProf.measure_mode

- lib/ruby-prof/printers/abstract_printer.rb
- test/printers_test.rb
This PR updates the `print_footer` function to make the metric descriptions dynamic based on the measurement mode used. The metric values (such as `time`, `allocations`, `memory`, etc.) are now adjusted dynamically based on the value of `@result.measure_mode`.
> Update description to use dynamic metrics
